[package]
  cjc-version = "1.1.0"
  name = "mmapcj"
  organization = ""
  description = "跨平台内存映射文件库 (Linux/macOS/Windows)"
  version = "1.0.1"
  target-dir = ""
  script-dir = ""
  src-dir = "src"
  output-type = "static"
  compile-option = "-O2"
  override-compile-option = ""
  link-option = ""
  include = ["/src"]
  license = ["Apache-2.0"]
  authors = ["ystyle"]
  repository = "https://atomgit.com/ystyle/mmap-cj"

[dependencies]
