name: Windows CI

on:
  push:
  workflow_dispatch:

jobs:
  test-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]      # x86_64（仓颉 Windows 原生 SDK：windows_x86_64_cjnative）
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Cangjie toolchain
        uses: Zxilly/setup-cangjie@v3
        with:
          channel: sts
          version: auto            # 从 cjpm.toml 读取 cjc-version = "1.1.0"

      - name: Test (os.windows)
        run: cjpm test            # @When[os == "Windows"] 自动选中 windows 实现
